name: ped
version: 0.0.4
author: Michael Haubenwallner <michael.haubenwallner@gmail.com>
description: polymer-element dependencies
homepage: https://github.com/d2m/ped
dependencies:
  html5lib: any
  path: any
  yaml: any
dev_dependencies:
  browser: any
  polymer: '>=0.10.0 <0.11.0'
  unittest: any
